### ISSUE TITLE
Problem with Writeconsoleoutputcharacter

### ISSUE THREAD

**Issue by ghost** [OneLoneCoder/CommandLineFPS#2]
![clfps](https://user-images.githubusercontent.com/34399010/46256526-a23f1280-c4b4-11e8-9973-1ee49f17bccb.PNG)
Where did I do wrong?

**Comment by Igor-Polatajko** [comment]
I had the same issue.

Just change 
    WriteConsoleOutputCharacter(hConsole, screen, nScreenWidth * nScreenHeight, { 0,0 }, 
    &dwBytesWritten);
To
    WriteConsoleOutputCharacterW(hConsole, screen, nScreenWidth * nScreenHeight, { 0,0 }, 
   &dwBytesWritten);

It should work))
