### ISSUE TITLE
swprint_s was not declared in this scope / C++ 

### ISSUE THREAD

**Issue by mrdcvlsc** [OneLoneCoder/CommandLineFPS#8]
the function "swprintf_s" was not declared says the compiler :(

i already included the "cstdio" "wchar.h", and the "stdio" but it is not working please help...

**Comment by ailijic** [comment]
You can comment it out; it is only printing out the player position and frame rate. I was able to get it to compile by changing it to "swprintf".

**Comment by emredav** [comment]
You can use " _snwprintf " or "snwprintf" if you use "swprintf" you will get error(invalid conversion from 'int' to 'const wchar_t*') .

`snwprintf(screen, 40, L"X=%3.2f, Y=%3.2f, A=%3.2f FPS=%3.2f ", fPlayerX, fPlayerY, fPlayerA, 1.0f/fElapsedTime);`

**Comment by chiboubys** [comment]
you can use:
`swprintf`
it will work for you

**Comment by mrdcvlsc** [comment]
wow I forgot to close this almost 3 years ago, late thanks everything is working! :)
